# -*- coding: utf-8 -*-
"""LessonThree:IntroductionToPythonForFianance

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZajANGSOy5pm_jyVGpOyv1IMCb3qUh5c

#Introduction
"""

#Q1
print(8 / 2)

#Q2
revenue_1 = 229.23
print(revenue_1)

#Q3
# Type of company_1
print(type(revenue_1))

#Q4
#Complete the sentence
sentence = 'The data type of revenue 1 is' + str(type(revenue_1)) + 'and it has a value of ' + str(revenue_1)
print(sentence)

"""#Lists"""

#Q1
# Create and print list names
names = ['Apple Inc', 'Coca-Cola', 'Walmart']
print(names)

# Create and print list prices
prices = [159.54, 37.13, 71.17]
print(prices)

#Q2
# Create and print the nested list stocks
stocks = [names, prices]
print(stocks)

# Use indexing to obtain 71.17
print(stocks[1][2])


#Q3
# Append a name to the list names
names.append('Amazon.com')
print(names)

# Extend list names
more_elements = ['DowDuPont', 'Alphabet Inc']
names.extend(more_elements)
print(names)

#Q4
# Do not modify this
max_price = max(prices)

# Identify index of max price
max_index = prices.index(max(prices))

# Identify the name of the company with max price
max_stock_name = names[max_index]

"""#Arrays"""

#Q1
# Import numpy as np
import numpy as np

# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)

#Q2
import pandas as pd
stock_array=pd.read_csv('stock_data.csv')

# Transpose stock_array
stock_array_transposed = np.transpose(stock_array)
print(stock_array_transposed)

# Print the shape of stock_array
print(stock_array_transposed.shape)

# Print the size of stock_array
print(stock_array_transposed.size)

#Q3
# Calculate the standard deviation
prices_std = np.std(prices)
print(prices_std)

#Q4
# Create and print company IDs
company_ids = np.arange(1, 8, 1)
print(company_ids)

# Use array slicing to select specific company IDs
company_ids_odd = np.arange(1, 8, 2)
print(company_ids_odd)

"""#Visualisations"""

#Q1
import pandas as pd
stock_A=pd.read_csv('stock_data.csv')
stock_B=pd.read_csv('stock_data2.csv')
days = stock_A['Day']
prices = stock_A['Price']

# Import matplotlib.pyplot with the alias plt
import matplotlib.pyplot as plt

# Plot the price of stock over time
plt.plot(days, prices, color="red", linestyle="--")

# Display the plot
plt.show()

#Q2
# Import pyplot as plt
import matplotlib.pyplot as plt

# Plot price as a function of time
plt.scatter(days, prices, color='green', s=0.1)

# Show plot
plt.show()

#Q3
# Plot histogram of stocks_A
plt.hist(stock_A, bins=100, alpha=0.4)

# Plot histogram of stocks_B
plt.hist(stock_B, bins=100, alpha=0.4)

# Display plot
plt.show()

#Q4
# Plot stock_A and stock_B histograms
plt.hist(stock_A, bins=100, alpha=0.4, label='Stock A')
plt.hist(stock_B, bins=100, alpha=0.4, label='Stock B')

# Add the legend
plt.legend()

# Display the plot
plt.show()